### ISSUE TITLE
reset-password gives Status Code: 404

### ISSUE THREAD

**Issue by Eir-nya** [LSchallot/JellyRoller#37] opened 2024-06-14 19:29 UTC
**Jellyfin version**: 10.9.2
**Jellyroller version**: 0.3.0

Using the `reset-password` subcommand returns the following output:

```
$ ./jellyroller reset-password test test2
Status Code: 404 Not Found
```

I've confirmed that the Jellyfin server is targeted correctly, as other subcommands (eg. `list-users`) give their expected output. Adding and deleting users also works as expected.

**Comment by LSchallot** [comment] 2024-06-15 01:02
I think this has something to do with your version of Jellyfin.  Testing out on 10.9.3 works properly, but I do remember several things being broken on 10.9.2.  I will setup a test environment to assure I am remembering correctly.

**Comment by Eir-nya** [comment] 2024-06-16 21:28
I just updated my Jellyfin docker image to the latest (Jellyfin version 10.9.6) and restarted. Same as before, `reset-password` gives a 404 error, while adding and removing users still works. So I don't think the version is the issue?

**Comment by LSchallot** [comment] 2024-06-17 02:44
Alright.  I can reproduce.  It is working in the 4.0 release which I will probably go ahead and push out in the next few days.  If you don't want to wait, you can build from the dev branch.

**Comment by LSchallot** [comment] 2024-07-01 00:31
This should be fixed as 0.4.0 has been released.  Please let me know if you are still having issues.

**Closed by LSchallot** 2024-07-01 00:31 UTC

**Comment by Eir-nya** [comment] 2024-07-05 00:40
Sorry for the late reply. There's no more 404 error now! However, regardless of the new password I input, the target account always seems to have *no* password other than a new one (ie. `"HasPassword"` is set to false in user props, no password is required on login). This seems unintended so I thought I'd let you know.

**Comment by LSchallot** [comment] 2024-07-06 04:13
Thank you very much for pointing this out.  Looks like the expected body of the request changed at some point and instead of throwing an error and rejecting it, Jellyfin just didn't accept a password.  I must have missed something in the doc changes.  JellyRoller 4.1 will have a fix.
